---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-mongo
  namespace: dbs
spec:
  storageClassName: slow
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/minio/data"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: dbs
spec:
  type: LoadBalancer
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo-database
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-mongo
  namespace: dbs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: slow
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongodb-deployemnt
  namespace: dbs
spec:
  selector:
    matchLabels:
      app: mongo-database
  strategy:
    type: Recreate
  template: 
    metadata:
      name: mongo-database
      labels:
        app: mongo-database
    spec:
      volumes:
      - name: data-mongo
        persistentVolumeClaim:
          claimName: data-mongo
      containers:
      - name: mongo-database
        image: mongo:4.2
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: data-mongo
          mountPath: /data/db
