apiVersion: v1
kind: Namespace
metadata:
  name: oidc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-oidc
  namespace: oidc
spec:
  ports:
    - port: 5432
      name: postgres
  selector:
    app: postgres-oidc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-oidc
  namespace: oidc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-oidc
  template:
    metadata:
      labels:
        app: postgres-oidc
    spec:
      containers:
        - name: postgres-oidc
          image: postgres:12-alpine
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oidc-secret
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: oidc-secret
                  key: username
            - name: POSTGRES_DB
              value: "keycloak"
          volumeMounts:
            - name: postgres-oidc-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-oidc-data
          persistentVolumeClaim:
            claimName: oidc-postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: oidc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycoak
          image:  jboss/keycloak
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: DB_VENDOR
              value: "postgres"
            - name: DB_ADDR
              value: "postgres-oidc"
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: "keycloak"
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: oidc-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oidc-secret
                  key: password
            - name: KEYCLOAK_USER
              valueFrom:
                secretKeyRef:
                  name: oidc-secret
                  key: username
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oidc-secret
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: oidc
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: http
      nodePort: 30100
      targetPort: 8080
  selector:
    app: keycloak
  type: NodePort
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: oidc-postgres
  namespace: oidc
spec:
  storageClassName: slow
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/postgresql/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oidc-postgres
  namespace: oidc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: slow
  resources:
    requests:
      storage: 4Gi
