apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bridgedb-app-secure
  namespace: bridge
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - bridgedb.cloud.nanosolveit.eu
    secretName: bridgedb-app-cert-ingress
  rules:
  - host: bridgedb.cloud.nanosolveit.eu
    http:
      paths:
      - backend:
          serviceName: bridgedb-app
          servicePort: 8183
        path: /
