kind: Service
apiVersion: v1
metadata:
  name: bridgedb-app
  namespace: bridge
spec:
  selector:
    app: bridgedb-app
  ports:
  - protocol: TCP
    port: 8183
    targetPort: 8183
---
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1
kind: Deployment
metadata:
  name: bridgedb-app
  namespace: bridge
spec:
  selector:
    matchLabels:
      app: bridgedb-app
  replicas: 1 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      name: bridgedb-app
      labels:
        app: bridgedb-app
    spec:
      containers:
      - name: bridgedb-app
        image: bigcatum/bridgedb:2.3.3
        ports:
        - containerPort: 8183
