kind: Service
apiVersion: v1
metadata:
  name: nanofase-app
  namespace: nanofase
spec:
  selector:
    app: nanofase-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1 
kind: Pod
metadata:
  name: nanofase-app
  namespace: nanofase
  labels:
    app: nanofase-app
spec:
  containers:
  - name: nanofase-app
    image: nanosolveit/nanofase:1.0.7
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html/conf
  initContainers:
  - name: config-data
    image: busybox
    command: ["sh","-c", "echo \"{\\\"nanoFaseApi\\\": \\\"https://nanofaseapi.cloud.nanosolveit.eu/\\\",\\\"stsServer\\\": \\\"https://login.cloud.nanosolveit.eu/auth/realms/nanosolveit\\\",\\\"redirect_url\\\" : \\\"https://nanofase.cloud.nanosolveit.eu/\\\",\\\"client_id\\\":\\\"nanofase-app\\\",\\\"response_type\\\" : \\\"id_token token\\\",\\\"scope\\\": \\\"openid email profile\\\",\\\"silent_redirect_url\\\" : \\\"https://nanofase.cloud.nanosolveit.eu/assets/silent-renew.html\\\"}\" > /work-dir/conf.json" ]
    volumeMounts:
    - name: workdir
      mountPath: "/work-dir"
  dnsPolicy: Default
  volumes:
  - name: workdir
    emptyDir: {}
---
