apiVersion: v1
kind: Service
metadata:
  name: minio-service-nodeport
  namespace: dbs
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      nodePort: 41427
  selector:
    app: minio
