kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-minio
  namespace: dbs
spec:
  storageClassName: slow
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/minio/data"
