kind: Service
apiVersion: v1
metadata:
  name: deepdaph-app
  namespace: deepdaph
spec:
  selector:
    app: deepdaph-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1 
kind: Pod
metadata:
  name: deepdaph-app
  namespace: deepdaph
  labels:
    app: deepdaph-app
spec:
  containers:
  - name: deepdaph-app
    image: nanosolveit/deepdaph
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html/conf
  initContainers:
  - name: config-data
    image: busybox
    command: ["sh","-c", "echo \"{\\\"deepdaphapi\\\": \\\"https://deepdaph-api.cloud.nanosolveit.eu/\\\",\\\"stsServer\\\": \\\"https://login.cloud.nanosolveit.eu/auth/realms/nanosolveit\\\",\\\"redirect_url\\\" : \\\"https://deepdaph.cloud.nanosolveit.eu/dashboard\\\",\\\"client_id\\\":\\\"deepdaph-app\\\",\\\"response_type\\\" : \\\"id_token token\\\",\\\"scope\\\": \\\"openid email profile\\\",\\\"silent_redirect_url\\\" : \\\"https://deepdaph.cloud.nanosolveit.eu/assets/silent-renew.html\\\"}\" > /work-dir/conf.json" ]
    volumeMounts:
    - name: workdir
      mountPath: "/work-dir"
  dnsPolicy: Default
  volumes:
  - name: workdir
    emptyDir: {}
---
