apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sapnets-app-secure
  namespace: qsarlab
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts: 
    - sapnets.cloud.nanosolveit.eu
    secretName: sapnets-app-cert
  rules:
  - host: sapnets.cloud.nanosolveit.eu
    http:
      paths:
      - backend:
          serviceName: qsar-service
          servicePort: 8050
        path: /
